config/routes.rb
Rails.application.routes.draw do
  resources :commentals

  resources :postals

  resources :posts

  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/commental.rb
class Commental < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/postal.rb
class Postal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/commentals_controller.rb
class CommentalsController < ApplicationController
  before_action :set_commental, only: [:show, :edit, :update, :destroy]

  # GET /commentals
  # GET /commentals.json
  def index
    @commentals = Commental.all
  end

  # GET /commentals/1
  # GET /commentals/1.json
  def show
  end

  # GET /commentals/new
  def new
    @commental = Commental.new
  end

  # GET /commentals/1/edit
  def edit
  end

  # POST /commentals
  # POST /commentals.json
  def create
    @commental = Commental.new(commental_params)

    respond_to do |format|
      if @commental.save
        format.html { redirect_to @commental, notice: 'Commental was successfully created.' }
        format.json { render :show, status: :created, location: @commental }
      else
        format.html { render :new }
        format.json { render json: @commental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commentals/1
  # PATCH/PUT /commentals/1.json
  def update
    respond_to do |format|
      if @commental.update(commental_params)
        format.html { redirect_to @commental, notice: 'Commental was successfully updated.' }
        format.json { render :show, status: :ok, location: @commental }
      else
        format.html { render :edit }
        format.json { render json: @commental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commentals/1
  # DELETE /commentals/1.json
  def destroy
    @commental.destroy
    respond_to do |format|
      format.html { redirect_to commentals_url, notice: 'Commental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commental
      @commental = Commental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commental_params
      params.require(:commental).permit(:post_id, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params[:comment]
    end
end

app/controllers/postals_controller.rb
class PostalsController < ApplicationController
  before_action :set_postal, only: [:show, :edit, :update, :destroy]

  # GET /postals
  # GET /postals.json
  def index
    @postals = Postal.all
  end

  # GET /postals/1
  # GET /postals/1.json
  def show
  end

  # GET /postals/new
  def new
    @postal = Postal.new
  end

  # GET /postals/1/edit
  def edit
  end

  # POST /postals
  # POST /postals.json
  def create
    @postal = Postal.new(postal_params)

    respond_to do |format|
      if @postal.save
        format.html { redirect_to @postal, notice: 'Postal was successfully created.' }
        format.json { render :show, status: :created, location: @postal }
      else
        format.html { render :new }
        format.json { render json: @postal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postals/1
  # PATCH/PUT /postals/1.json
  def update
    respond_to do |format|
      if @postal.update(postal_params)
        format.html { redirect_to @postal, notice: 'Postal was successfully updated.' }
        format.json { render :show, status: :ok, location: @postal }
      else
        format.html { render :edit }
        format.json { render json: @postal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postals/1
  # DELETE /postals/1.json
  def destroy
    @postal.destroy
    respond_to do |format|
      format.html { redirect_to postals_url, notice: 'Postal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postal
      @postal = Postal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postal_params
      params.require(:postal).permit(:title, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params[:post]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commentals_helper.rb
module CommentalsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/postals_helper.rb
module PostalsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/commentals/_form.html.erb
<%= form_for(@commental) do |f| %>
  <% if @commental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commental.errors.count, "error") %> prohibited this commental from being saved:</h2>

      <ul>
      <% @commental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commentals/edit.html.erb
<h1>Editing commental</h1>

<%= render 'form' %>

<%= link_to 'Show', @commental %> |
<%= link_to 'Back', commentals_path %>

app/views/commentals/index.html.erb
<h1>Listing commentals</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commentals.each do |commental| %>
      <tr>
        <td><%= commental.post_id %></td>
        <td><%= commental.body %></td>
        <td><%= link_to 'Show', commental %></td>
        <td><%= link_to 'Edit', edit_commental_path(commental) %></td>
        <td><%= link_to 'Destroy', commental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commental', new_commental_path %>

app/views/commentals/new.html.erb
<h1>New commental</h1>

<%= render 'form' %>

<%= link_to 'Back', commentals_path %>

app/views/commentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @commental.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @commental.body %>
</p>

<%= link_to 'Edit', edit_commental_path(@commental) %> |
<%= link_to 'Back', commentals_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssignmentBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/postals/_form.html.erb
<%= form_for(@postal) do |f| %>
  <% if @postal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@postal.errors.count, "error") %> prohibited this postal from being saved:</h2>

      <ul>
      <% @postal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/postals/edit.html.erb
<h1>Editing postal</h1>

<%= render 'form' %>

<%= link_to 'Show', @postal %> |
<%= link_to 'Back', postals_path %>

app/views/postals/index.html.erb
<h1>Listing postals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postals.each do |postal| %>
      <tr>
        <td><%= postal.title %></td>
        <td><%= postal.body %></td>
        <td><%= link_to 'Show', postal %></td>
        <td><%= link_to 'Edit', edit_postal_path(postal) %></td>
        <td><%= link_to 'Destroy', postal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Postal', new_postal_path %>

app/views/postals/new.html.erb
<h1>New postal</h1>

<%= render 'form' %>

<%= link_to 'Back', postals_path %>

app/views/postals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @postal.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @postal.body %>
</p>

<%= link_to 'Edit', edit_postal_path(@postal) %> |
<%= link_to 'Back', postals_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>